from lista_circular_simple import ListaCircularSimple
lista = ListaCircularSimple()

lista.agregarFinal(5)
lista.agregarFinal(6)
lista.agregarFinal(7)
lista.agregarFinal(8)
lista.agregarFinal(9)
lista.agregarFinal(10)
lista.agregarInicio(4)
lista.agregarInicio(3)
lista.agregarInicio(2)
lista.agregarInicio(1)
lista.removerInicio()
lista.removerFinal()
lista.recorrer()
print('Primero:',lista.primero)
print('Ultimo:',lista.ultimo.dato)
print('Ultimo_Siguiente:',lista.ultimo.siguiente)
