/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

/**
 *
 * @author bmfil
 */
public class dlg_Libros extends javax.swing.JDialog {

    /**
     * Creates new form Insertar_libros
     */
    public dlg_Libros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEdit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jdFechaPu = new com.toedter.calendar.JDateChooser();
        txtNumero = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtExist = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnCancelarLi = new javax.swing.JButton();
        btnVolverALi = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnAgregarLi1 = new javax.swing.JButton();
        btnBuscarli = new javax.swing.JButton();
        btnLimpiarli = new javax.swing.JButton();
        btnNuevoli = new javax.swing.JButton();
        cmbCategoria = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        cmbIdAutor = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Categoria");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 150, 76, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Autor");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 220, 76, 21);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Editorial");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 290, 76, 16);

        txtEdit.setEnabled(false);
        getContentPane().add(txtEdit);
        txtEdit.setBounds(30, 310, 112, 22);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Fecha de publicacion");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 360, 160, 21);

        jdFechaPu.setEnabled(false);
        getContentPane().add(jdFechaPu);
        jdFechaPu.setBounds(30, 390, 130, 22);

        txtNumero.setEnabled(false);
        getContentPane().add(txtNumero);
        txtNumero.setBounds(190, 180, 140, 22);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Numero de paginas");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(190, 150, 170, 21);

        txtExist.setEnabled(false);
        getContentPane().add(txtExist);
        txtExist.setBounds(190, 240, 112, 22);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Existencia");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(190, 220, 90, 21);

        txtPrecio.setEnabled(false);
        getContentPane().add(txtPrecio);
        txtPrecio.setBounds(190, 310, 112, 22);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Precio");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(190, 290, 50, 21);

        btnCancelarLi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCancelarLi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/prohibicion.png"))); // NOI18N
        btnCancelarLi.setText("Cancelar");
        btnCancelarLi.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 0, 102)));
        btnCancelarLi.setEnabled(false);
        getContentPane().add(btnCancelarLi);
        btnCancelarLi.setBounds(150, 480, 90, 30);

        btnVolverALi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnVolverALi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/girar-a-la-izquierda.png"))); // NOI18N
        btnVolverALi.setText("Volver");
        btnVolverALi.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 0, 102)));
        getContentPane().add(btnVolverALi);
        btnVolverALi.setBounds(260, 480, 90, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("       ¬¬¬ LIBROS ¬¬¬");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 10, 235, 32);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 50);

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));

        jPanel4.setBackground(new java.awt.Color(255, 255, 102));
        jPanel2.add(jPanel4);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(350, 50, 50, 490);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Codigo");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 70, 76, 20);
        getContentPane().add(txtCodigo);
        txtCodigo.setBounds(30, 100, 112, 22);

        btnAgregarLi1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAgregarLi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/libro (1).png"))); // NOI18N
        btnAgregarLi1.setText("Agregar");
        btnAgregarLi1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 0, 102)));
        btnAgregarLi1.setEnabled(false);
        getContentPane().add(btnAgregarLi1);
        btnAgregarLi1.setBounds(260, 110, 80, 30);

        btnBuscarli.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnBuscarli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/busqueda.png"))); // NOI18N
        btnBuscarli.setText("Buscar");
        btnBuscarli.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 0, 102)));
        getContentPane().add(btnBuscarli);
        btnBuscarli.setBounds(150, 90, 85, 30);

        btnLimpiarli.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnLimpiarli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/escoba.png"))); // NOI18N
        btnLimpiarli.setText("limpiar");
        btnLimpiarli.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 0, 102)));
        getContentPane().add(btnLimpiarli);
        btnLimpiarli.setBounds(30, 480, 90, 26);

        btnNuevoli.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnNuevoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/agregar.png"))); // NOI18N
        btnNuevoli.setText("Nuevo");
        btnNuevoli.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 0, 102)));
        getContentPane().add(btnNuevoli);
        btnNuevoli.setBounds(260, 70, 80, 26);

        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione categoria", "Informativos", "literarios", "Historicos", "biograficos", "enciclopedia", "artisticos", "cientificos", "Ficción ", "Fantasía", "Realismo mágico", "Distopia", "Romance", "Suspenso" }));
        cmbCategoria.setEnabled(false);
        getContentPane().add(cmbCategoria);
        cmbCategoria.setBounds(30, 180, 140, 22);

        jPanel3.setBackground(new java.awt.Color(255, 255, 102));
        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 50, 30, 490);

        jPanel5.setBackground(new java.awt.Color(255, 255, 102));
        getContentPane().add(jPanel5);
        jPanel5.setBounds(20, 510, 330, 30);

        cmbIdAutor.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmbIdAutor.setEnabled(false);
        getContentPane().add(cmbIdAutor);
        cmbIdAutor.setBounds(30, 250, 140, 27);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlg_Libros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlg_Libros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlg_Libros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlg_Libros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarLi1;
    public javax.swing.JButton btnBuscarli;
    public javax.swing.JButton btnCancelarLi;
    public javax.swing.JButton btnLimpiarli;
    public javax.swing.JButton btnNuevoli;
    public javax.swing.JButton btnVolverALi;
    public javax.swing.JComboBox<String> cmbCategoria;
    public javax.swing.JComboBox<String> cmbIdAutor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public com.toedter.calendar.JDateChooser jdFechaPu;
    public javax.swing.JTextField txtCodigo;
    public javax.swing.JTextField txtEdit;
    public javax.swing.JTextField txtExist;
    public javax.swing.JTextField txtNumero;
    public javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
