/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

/**
 *
 * @author Equipo
 */
public class dlg_Mostrar extends javax.swing.JDialog {

    /**
     * Creates new form Mostrar
     */
    public dlg_Mostrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMostrarMenuT = new javax.swing.JButton();
        btnMostrarVolver = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMostrar = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btnMostrarMenuT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnMostrarMenuT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/nota.png"))); // NOI18N
        btnMostrarMenuT.setText("Menu de Tablas");
        btnMostrarMenuT.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(btnMostrarMenuT);
        btnMostrarMenuT.setBounds(250, 330, 130, 30);

        btnMostrarVolver.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnMostrarVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/girar-a-la-izquierda.png"))); // NOI18N
        btnMostrarVolver.setText("Volver");
        btnMostrarVolver.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(btnMostrarVolver);
        btnMostrarVolver.setBounds(70, 330, 110, 30);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText(":: M O S T R A R ::");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 10, 201, 29);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 450, 60);

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 360, 450, 30);

        jTableMostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableMostrar);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 60, 420, 260);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlg_Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlg_Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlg_Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlg_Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnMostrarMenuT;
    public javax.swing.JButton btnMostrarVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTableMostrar;
    // End of variables declaration//GEN-END:variables
}
