/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

/**
 *
 * @author Equipo
 */
public class dlg_Menu extends javax.swing.JDialog {

    /**
     * Creates new form Menu
     */
    public dlg_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMenuAut = new javax.swing.JButton();
        btnMenuEst = new javax.swing.JButton();
        btnMenuPres = new javax.swing.JButton();
        btnMenuLib = new javax.swing.JButton();
        btnMenuDev = new javax.swing.JButton();
        btnMenuCerrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btnMenuAut.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnMenuAut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/editor.png"))); // NOI18N
        btnMenuAut.setText("Autores");
        btnMenuAut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 255)));
        getContentPane().add(btnMenuAut);
        btnMenuAut.setBounds(50, 110, 160, 30);

        btnMenuEst.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnMenuEst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/estudiantes.png"))); // NOI18N
        btnMenuEst.setText("Estudiantes");
        btnMenuEst.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 255)));
        getContentPane().add(btnMenuEst);
        btnMenuEst.setBounds(50, 70, 160, 30);

        btnMenuPres.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnMenuPres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/costo-de-educacion.png"))); // NOI18N
        btnMenuPres.setText("Prestamos");
        btnMenuPres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 255)));
        btnMenuPres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPresActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenuPres);
        btnMenuPres.setBounds(50, 150, 160, 30);

        btnMenuLib.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnMenuLib.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/libros (1).png"))); // NOI18N
        btnMenuLib.setText("Libros");
        btnMenuLib.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 255)));
        getContentPane().add(btnMenuLib);
        btnMenuLib.setBounds(50, 190, 160, 30);

        btnMenuDev.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnMenuDev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/libro (2).png"))); // NOI18N
        btnMenuDev.setText("Devoluciones");
        btnMenuDev.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 255)));
        getContentPane().add(btnMenuDev);
        btnMenuDev.setBounds(50, 230, 160, 30);

        btnMenuCerrar.setBackground(new java.awt.Color(204, 204, 255));
        btnMenuCerrar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnMenuCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/boton.png"))); // NOI18N
        btnMenuCerrar.setText("Cerrar");
        btnMenuCerrar.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(btnMenuCerrar);
        btnMenuCerrar.setBounds(170, 310, 75, 20);

        jPanel1.setBackground(new java.awt.Color(153, 102, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/biblioteca.png"))); // NOI18N
        jLabel1.setText("MENU ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 10, 130, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 260, 60);

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 340, 260, 40);

        btnMostrar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/busqueda.png"))); // NOI18N
        btnMostrar.setText("Mostrar");
        btnMostrar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 255)));
        getContentPane().add(btnMostrar);
        btnMostrar.setBounds(50, 270, 160, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuPresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuPresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlg_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlg_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlg_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlg_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnMenuAut;
    public javax.swing.JButton btnMenuCerrar;
    public javax.swing.JButton btnMenuDev;
    public javax.swing.JButton btnMenuEst;
    public javax.swing.JButton btnMenuLib;
    public javax.swing.JButton btnMenuPres;
    public javax.swing.JButton btnMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
