/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

public class dlg_Estudiantes extends javax.swing.JDialog {

    public dlg_Estudiantes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNuevoestu = new javax.swing.JButton();
        btnAgregaNuevoestu = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtTelefonoestu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreEstu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtcorreoestu = new javax.swing.JTextField();
        btnLImpiarestu = new javax.swing.JButton();
        btnVolverestu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnBuscarestu = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtMatriculaestu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbCarreraEstu = new javax.swing.JComboBox<>();
        btnCancelarEstu = new javax.swing.JButton();
        btnDeshabilitarEstu = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtAdeudoEstu = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btnNuevoestu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnNuevoestu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/agregar.png"))); // NOI18N
        btnNuevoestu.setText("Nuevo");
        btnNuevoestu.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 153, 0)));
        getContentPane().add(btnNuevoestu);
        btnNuevoestu.setBounds(330, 80, 110, 35);

        btnAgregaNuevoestu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAgregaNuevoestu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cliente.png"))); // NOI18N
        btnAgregaNuevoestu.setText("Agregar ");
        btnAgregaNuevoestu.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 153, 0)));
        btnAgregaNuevoestu.setEnabled(false);
        getContentPane().add(btnAgregaNuevoestu);
        btnAgregaNuevoestu.setBounds(330, 180, 110, 35);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Carrera");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 250, 60, 20);

        txtTelefonoestu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTelefonoestu.setEnabled(false);
        getContentPane().add(txtTelefonoestu);
        txtTelefonoestu.setBounds(90, 300, 200, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Telefono");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 300, 82, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 170, 70, 20);

        txtNombreEstu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNombreEstu.setEnabled(false);
        getContentPane().add(txtNombreEstu);
        txtNombreEstu.setBounds(90, 170, 200, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Correo");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 210, 60, 20);

        txtcorreoestu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtcorreoestu.setEnabled(false);
        getContentPane().add(txtcorreoestu);
        txtcorreoestu.setBounds(90, 210, 200, 20);

        btnLImpiarestu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnLImpiarestu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/escoba.png"))); // NOI18N
        btnLImpiarestu.setText("Limpiar");
        btnLImpiarestu.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 153, 0)));
        btnLImpiarestu.setEnabled(false);
        getContentPane().add(btnLImpiarestu);
        btnLImpiarestu.setBounds(330, 280, 110, 35);

        btnVolverestu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnVolverestu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/volver.png"))); // NOI18N
        btnVolverestu.setText("Volver");
        btnVolverestu.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 153, 0)));
        getContentPane().add(btnVolverestu);
        btnVolverestu.setBounds(330, 380, 110, 40);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText(" --- ESTUDIANTES ---");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 10, 229, 32);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 460, 60);

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 430, 460, 50);

        btnBuscarestu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnBuscarestu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/buscar.png"))); // NOI18N
        btnBuscarestu.setText("Buscar");
        btnBuscarestu.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 153, 0)));
        getContentPane().add(btnBuscarestu);
        btnBuscarestu.setBounds(330, 130, 110, 35);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Matricula");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 130, 70, 20);

        txtMatriculaestu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtMatriculaestu);
        txtMatriculaestu.setBounds(90, 130, 200, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/graduado.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 60, 30, 40);

        cmbCarreraEstu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmbCarreraEstu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carreras Universitarias", "Ingeniería", "Medicina", "Derecho", "Psicología", "Arquitectura", "Economía" }));
        cmbCarreraEstu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmbCarreraEstu.setEnabled(false);
        getContentPane().add(cmbCarreraEstu);
        cmbCarreraEstu.setBounds(90, 250, 203, 27);

        btnCancelarEstu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCancelarEstu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/prohibicion.png"))); // NOI18N
        btnCancelarEstu.setText("Cancelar");
        btnCancelarEstu.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 153, 0)));
        btnCancelarEstu.setEnabled(false);
        getContentPane().add(btnCancelarEstu);
        btnCancelarEstu.setBounds(330, 330, 110, 35);

        btnDeshabilitarEstu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnDeshabilitarEstu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/portapapeles.png"))); // NOI18N
        btnDeshabilitarEstu.setText("Deshabilitar");
        btnDeshabilitarEstu.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 153, 0)));
        btnDeshabilitarEstu.setEnabled(false);
        getContentPane().add(btnDeshabilitarEstu);
        btnDeshabilitarEstu.setBounds(330, 230, 110, 35);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Adeudo");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 340, 82, 20);

        txtAdeudoEstu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtAdeudoEstu.setEnabled(false);
        getContentPane().add(txtAdeudoEstu);
        txtAdeudoEstu.setBounds(90, 340, 200, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlg_Estudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlg_Estudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlg_Estudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlg_Estudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregaNuevoestu;
    public javax.swing.JButton btnBuscarestu;
    public javax.swing.JButton btnCancelarEstu;
    public javax.swing.JButton btnDeshabilitarEstu;
    public javax.swing.JButton btnLImpiarestu;
    public javax.swing.JButton btnNuevoestu;
    public javax.swing.JButton btnVolverestu;
    public javax.swing.JComboBox<String> cmbCarreraEstu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField txtAdeudoEstu;
    public javax.swing.JTextField txtMatriculaestu;
    public javax.swing.JTextField txtNombreEstu;
    public javax.swing.JTextField txtTelefonoestu;
    public javax.swing.JTextField txtcorreoestu;
    // End of variables declaration//GEN-END:variables
}
