/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

/**
 *
 * @author Equipo
 */
public class dlg_Devoluciones extends javax.swing.JDialog {

    /**
     * Creates new form Devoluciones
     */
    public dlg_Devoluciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoDevolucion = new javax.swing.JTextField();
        txtIDPrestamodevo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCostodevo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jDFEchaDevo = new com.toedter.calendar.JDateChooser();
        txtSubtotaldevo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDiasdevo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIVAdevo = new javax.swing.JTextField();
        btnBuscardevo = new javax.swing.JButton();
        btnLimpiardevo = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnCancelardevo = new javax.swing.JButton();
        btnVolverDevo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnDevolverdevo = new javax.swing.JButton();
        btnAgregardevo = new javax.swing.JButton();
        btnNuevodevo = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();

        jLabel10.setText("Id Detalle Prestamo ");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Codigo");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 70, 60, 21);
        getContentPane().add(txtCodigoDevolucion);
        txtCodigoDevolucion.setBounds(6, 97, 112, 22);

        txtIDPrestamodevo.setEnabled(false);
        getContentPane().add(txtIDPrestamodevo);
        txtIDPrestamodevo.setBounds(290, 100, 100, 22);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Costo por dias");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 140, 120, 21);

        txtCostodevo.setEnabled(false);
        getContentPane().add(txtCostodevo);
        txtCostodevo.setBounds(140, 170, 120, 22);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Fecha de devolucion");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 70, 150, 21);

        jDFEchaDevo.setEnabled(false);
        getContentPane().add(jDFEchaDevo);
        jDFEchaDevo.setBounds(130, 100, 150, 24);

        txtSubtotaldevo.setEnabled(false);
        getContentPane().add(txtSubtotaldevo);
        txtSubtotaldevo.setBounds(140, 230, 112, 22);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Subtotal");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 200, 70, 21);

        txtDiasdevo.setEnabled(false);
        getContentPane().add(txtDiasdevo);
        txtDiasdevo.setBounds(10, 170, 112, 22);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Dias de retraso");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 140, 112, 21);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Iva");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 210, 30, 16);

        txtIVAdevo.setEnabled(false);
        getContentPane().add(txtIVAdevo);
        txtIVAdevo.setBounds(10, 230, 112, 22);

        btnBuscardevo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnBuscardevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/buscar.png"))); // NOI18N
        btnBuscardevo.setText("Buscar");
        btnBuscardevo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 51, 255)));
        getContentPane().add(btnBuscardevo);
        btnBuscardevo.setBounds(20, 120, 85, 20);

        btnLimpiardevo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnLimpiardevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/escoba.png"))); // NOI18N
        btnLimpiardevo.setText("Limpiar");
        btnLimpiardevo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 255)));
        getContentPane().add(btnLimpiardevo);
        btnLimpiardevo.setBounds(220, 300, 90, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Id Prestamo ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(300, 70, 100, 21);

        btnCancelardevo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCancelardevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/prohibicion.png"))); // NOI18N
        btnCancelardevo.setText("Cancelar");
        btnCancelardevo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 255)));
        btnCancelardevo.setEnabled(false);
        getContentPane().add(btnCancelardevo);
        btnCancelardevo.setBounds(20, 300, 90, 30);

        btnVolverDevo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnVolverDevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/volver.png"))); // NOI18N
        btnVolverDevo.setText("Volver");
        btnVolverDevo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 255)));
        getContentPane().add(btnVolverDevo);
        btnVolverDevo.setBounds(120, 300, 90, 30);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, -20, 60, 20);

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText(" :: DEVOLUCIONES ::");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(100, 10, 240, 32);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 400, 50);

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 340, 400, 40);

        btnDevolverdevo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnDevolverdevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/libro (2).png"))); // NOI18N
        btnDevolverdevo.setText("Devolver");
        btnDevolverdevo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 51, 255)));
        btnDevolverdevo.setEnabled(false);
        btnDevolverdevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverdevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnDevolverdevo);
        btnDevolverdevo.setBounds(300, 260, 90, 30);

        btnAgregardevo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAgregardevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/nota.png"))); // NOI18N
        btnAgregardevo.setText("Agregar");
        btnAgregardevo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 51, 255)));
        btnAgregardevo.setEnabled(false);
        getContentPane().add(btnAgregardevo);
        btnAgregardevo.setBounds(300, 220, 90, 30);

        btnNuevodevo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnNuevodevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/agregar.png"))); // NOI18N
        btnNuevodevo.setText("Nuevo");
        btnNuevodevo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 51, 255)));
        getContentPane().add(btnNuevodevo);
        btnNuevodevo.setBounds(300, 140, 90, 30);

        btnCalcular.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/costo-de-educacion (1).png"))); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 51, 255)));
        btnCalcular.setEnabled(false);
        getContentPane().add(btnCalcular);
        btnCalcular.setBounds(300, 180, 90, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDevolverdevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverdevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDevolverdevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlg_Devoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlg_Devoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlg_Devoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlg_Devoluciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregardevo;
    public javax.swing.JButton btnBuscardevo;
    public javax.swing.JButton btnCalcular;
    public javax.swing.JButton btnCancelardevo;
    public javax.swing.JButton btnDevolverdevo;
    public javax.swing.JButton btnLimpiardevo;
    public javax.swing.JButton btnNuevodevo;
    public javax.swing.JButton btnVolverDevo;
    public com.toedter.calendar.JDateChooser jDFEchaDevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JTextField txtCodigoDevolucion;
    public javax.swing.JTextField txtCostodevo;
    public javax.swing.JTextField txtDiasdevo;
    public javax.swing.JTextField txtIDPrestamodevo;
    public javax.swing.JTextField txtIVAdevo;
    public javax.swing.JTextField txtSubtotaldevo;
    // End of variables declaration//GEN-END:variables
}
